# Generated by Django 3.0.6 on 2020-05-19 12:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='', verbose_name='Титульне зображення')),
                ('text', models.TextField(verbose_name='Текст статті')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата написання')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата останнього редагування')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25, verbose_name='Теги'), size=None)),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ('-created',),
            },
        ),
    ]
