# Generated by Django 3.0.6 on 2020-05-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0003_auto_20200519_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PlantPost',
        ),
    ]
