# Generated by Django 3.0.6 on 2020-05-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0004_auto_20200521_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantpost',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Титульне зображення'),
        ),
    ]
